### ISSUE TITLE
源代码

### ISSUE THREAD

**Issue by liuflylove666** [hcymysql/MHA-Re-Edition#1]
请问有源代码下载地址没

**Comment by hcymysql** [comment]
> 

已跟进。

**Comment by Aaron-kk** [comment]
> > 同问。
> > 密码有特殊字符，调整下方法 configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%a'
> 
> 已解决，重新拉取可执行文件覆盖即可。我这边测试的密码是：password = **O@pl/GI:4i&&3a$8**

已测试 正常了，感谢。
ps：如果可以支持密码不使用明文配置就更好了^^

**Comment by Aaron-kk** [comment]
局部变量问题，麻烦看下
Traceback (most recent call last):
  File "masterha_manager_mysql.py", line 963, in <module>
  File "masterha_manager_mysql.py", line 409, in MasterMonitor
UnboundLocalError: local variable 'current_master_ssh_info' referenced before assignment

**Comment by hcymysql** [comment]
> current_master_ssh_info
Centos6系统 /sbin/ip;
Centos7系统 /usr/sbin/ip

Cenots6系统创建一个软连接：
ln  -s   /sbin/ip   /usr/sbin/ip

app1.cnf配置文件
[server1]
ip = 172.19.136.32
port = 3306
user = special_character
password = O@pl/GI:4i&&3a$8
ssh_user = root
ssh_port = 22
ssh_password = 123456

[server2]
ip = 172.19.136.33
port = 3307
user = special_character
password = O@pl/GI:4i&&3a$8
ssh_user = root
ssh_port = 22
ssh_password = 123456

[server3]
ip = 172.19.136.34
port = 3308
user = special_character
password = O@pl/GI:4i&&3a$8
ssh_user = root
ssh_port = 22
ssh_password = 123456

**Comment by liuflylove666** [comment]
@hcymysql 源码开放吗？

**Comment by Aaron-kk** [comment]
> UnboundLocalError: local variable 'current_master_ssh_info' referenced before assignment
>> Cenots6系统创建一个软连接：
>> ln -s /sbin/ip /usr/sbin/ip
我这边测试机器是Centos7，报错应该不是ip命令的原因，看起来是变量引用的问题 @hcymysql

**Comment by hcymysql** [comment]
> 

请问一下，你那边的环境是怎样的？是3台机器部署的MYSQL主从复制集群吗？

**Comment by hcymysql** [comment]
> > > UnboundLocalError: local variable 'current_master_ssh_info' referenced before assignment
> > > Cenots6系统创建一个软连接：
> > > ln -s /sbin/ip /usr/sbin/ip
> 
> 我这边测试机器是Centos7，报错应该不是ip命令的原因，看起来是变量引用的问题 @hcymysql

请再重新拉取一下masterha_manager_mysql这个文件，我增加了一个变量声明。

**Comment by Aaron-kk** [comment]
> > 
> 
> 请问一下，你那边的环境是怎样的？是3台机器部署的MYSQL主从复制集群吗？

我这边是mysql5.7.22 一主两从3个实例（这里的主是跨机房级联的2级从库），分别部署在三台物理机Centos7.9 内核4.20，端口一致，网卡做了team聚合。

拉取了最新的可执行文件，报错如下
Traceback (most recent call last):
  File "masterha_manager_mysql.py", line 963, in <module>
  File "masterha_manager_mysql.py", line 410, in MasterMonitor
IndexError: list index out of range

**Comment by hcymysql** [comment]
> > > 
> > 
> > 
> > 请问一下，你那边的环境是怎样的？是3台机器部署的MYSQL主从复制集群吗？
> 
> 我这边是mysql5.7.22 一主两从3个实例（这里的主是跨机房级联的2级从库），分别部署在三台物理机Centos7.9 内核4.20，端口一致，网卡做了team聚合。
> 
> 拉取了最新的可执行文件，报错如下 Traceback (most recent call last): File "masterha_manager_mysql.py", line 963, in File "masterha_manager_mysql.py", line 410, in MasterMonitor IndexError: list index out of range

请问第一步./masterha_check_repl_mysql  --conf=app1.cnf  环境配置测试通过吗？

**Comment by Aaron-kk** [comment]
> 
> 请问第一步./masterha_check_repl_mysql --conf=app1.cnf 环境配置测试通过吗？

通过的

**Comment by hcymysql** [comment]
你这样，用一个vmware虚拟3台centos7，安装MySQL5.7，干净的环境。你再试试。

我这边测试，没有问题的。

**Comment by Aaron-kk** [comment]
好的，我测试下

**Comment by hcymysql** [comment]
> 请问有源代码下载地址没

已开放下载。
