### ISSUE TITLE
当主库遇到网络问题时，无法进行切换

### ISSUE THREAD

**Issue by kevinconan** [hcymysql/MHA-Re-Edition#8]
直接干掉主库的网络连接，脚本执行故障切换的时候仍然会SSH去连接主库服务器删除VIP，但是会出现SSH失败，脚本直接挂掉

```shell
Thu Nov 24 20:45:58 2022 - [ERROR] 主库尝试连接3次后继续失败.
主机：10.105.255.169 ssh连接失败!!! 错误信息：timed out 
Traceback (most recent call last):
  File "masterha_manager_mysql.py", line 978, in <module>
  File "masterha_manager_mysql.py", line 484, in MasterMonitor
  File "masterha_manager_mysql.py", line 252, in ssh_exec
  File "paramiko/client.py", line 510, in exec_command
AttributeError: 'NoneType' object has no attribute 'open_session'
[473316] Failed to execute script 'masterha_manager_mysql' due to unhandled exception!
```

**Comment by hcymysql** [comment]
已确认BUG，正在修改。

**Comment by hcymysql** [comment]
已修复，重新拉取文件覆盖即可。
